### ISSUE TITLE
Sometime crash in function  executeTask() in class Integrator

### ISSUE THREAD

**Issue by QuyetND** [congncif/IDMCore#1]
Bug recorded in Fabric.

**Comment by congncif** [comment]
Hi, 

The Integrator runs its calls on background queue by default. However there are some tasks you must call them on main queue such as UI-related tasks, working location service, handling a in app purchase process,...

It's hard to say a reason exactly. But using incorrect queue might be cause crashes.
Please check your code and make sure, these tasks were called on right queue.

try it
```swift
integrator.prepareCall()
...
.call(queue: .main, delay: 0.1)
```

**Comment by QuyetND** [comment]
Thank you. I’ll review code and check fabric on next build version :)
