### ISSUE TITLE
crash all the time

### ISSUE THREAD

**Issue by liuhe-trec** [congncif/IDMCore#2]
When my project integrates this framework, crash often happens.
file： Integrator.swift
Number of lines of code： 226
infoQueue unexpectedly nil, so it crash!
Hope to give me valuable advice

**Comment by congncif** [comment]
Hi,
I don't know what version you are using. But `infoQueue` property is not available in latest version. So the advice is you should have an upgrade and rebuild with clean action.

**Comment by liuhe-trec** [comment]
2.6.10  the version we using

**Comment by congncif** [comment]
Latest version is 3.1.2. It's time for upgrading. 😄
