### ISSUE TITLE
'IDMCore', '2.6.10' application crashes

### ISSUE THREAD

**Issue by 10153375** [congncif/IDMCore#3]
Hello, using the 2.6.10 version of the program often crashes. Checking the log is that there is an error in the infoqueue. Removefirst() method in the integrator file. I tried to determine whether it is empty, but still reported an error. What can I do to avoid this error without upgrading the version? If you change this to infoqueue. Removeall(), what will be the impact on the data request?

**Comment by congncif** [comment]
Hi friend,
Thanks for your feedback. Your issue may be duplicated with some closed issues
https://github.com/congncif/IDMCore/issues/1
https://github.com/congncif/IDMCore/issues/2
Please update IDMCore version to fix them!
